"""
MediShop Pro — Shared data: products, doctors, departments
XLM-RoBERTa transformer for sentiment scoring (free, multilingual, best for reviews)
"""
from functools import lru_cache

# ── XLM-RoBERTa sentiment pipeline (lazy loaded) ──────────────────
_pipe = None
def get_pipe():
    global _pipe
    if _pipe is None:
        try:
            from transformers import pipeline
            _pipe = pipeline("sentiment-analysis",
                             model="cardiffnlp/twitter-xlm-roberta-base-sentiment",
                             max_length=512, truncation=True)
        except Exception:
            _pipe = None
    return _pipe

def xlm_score(texts: list) -> int:
    """
    Returns COUNT of positive reviews (integer 0 to len(texts), max 10).

    Logic:
      - If XLM-RoBERTa model is available: count reviews labelled 'positive'
      - Fallback: EVERY review is assumed positive by default.
        Only subtract if the review contains a clear negative word
        (English, Hindi Unicode, or Gujarati Unicode).
        This fixes the problem where neutral English reviews
        like "Trusted brand Cipla top quality" were not being counted
        because they had no keyword match.
    """
    pipe = get_pipe()
    if pipe and texts:
        try:
            results = pipe(texts[:10])
            pos = sum(1 for r in results if r['label'] == 'positive')
            return pos
        except Exception:
            pass

    # ── Keyword fallback ──────────────────────────────────────────
    # English negatives
    NEG_EN = [
        'bad','poor','worst','terrible','horrible','useless','waste','fake',
        'awful','disappointing','broken','pathetic','ineffective','wrong',
        'side effect','no improvement','did not work','not work','no result',
        'no effect','no benefit','no difference','money wasted','waste of money',
    ]
    # Hindi negatives (Unicode — actual Devanagari script)
    NEG_HI = [
        'बेकार','खराब','बुरा','बर्बाद','फायदा नहीं','कोई फायदा नहीं',
        'बहुत बुरा','कोई असर नहीं','पैसे बर्बाद','कोई फर्क नहीं',
        'साइड इफेक्ट','नहीं हुआ','बहुत खराब',
    ]
    # Gujarati negatives (Unicode — actual Gujarati script)
    NEG_GU = [
        'ખૂબ ખરાબ','બેકાર','ખૂબ નિરાશ','ફાયદો ઓછો','ફાયદો ન થયો',
        'પૈસા બગડ્યા','ફર્ક નથી','ફર્ક ન પડ્યો','ખૂબ ખરાબ',
        'કોઈ ફરક નથી','કોઈ ફાયદો ન','ખૂબ ખરાબ ક્વોલિટી',
    ]
    NEG_ALL = NEG_EN + NEG_HI + NEG_GU

    pos = 0
    for t in texts:
        tl = t.lower()
        # default: count as positive
        # only skip if review contains a negative signal
        is_negative = any(w in tl for w in NEG_ALL)
        if not is_negative:
            pos += 1
    return pos

@lru_cache(maxsize=256)
def cached_xlm(reviews_tuple: tuple) -> int:
    return xlm_score(list(reviews_tuple))

def product_nlp_score(p: dict) -> float:
    """
    Score = positive_count * 0.6 + rating * 0.4
    positive_count : 0-10  (positive reviews detected by NLP)
    rating         : 0-5   (star rating)
    Max possible   : 10*0.6 + 5*0.4 = 8.0
    """
    reviews = p.get('reviews', [])
    pos = cached_xlm(tuple(reviews)) if reviews else 7
    return round(pos * 0.6 + p['rating'] * 0.4, 1)

def doctor_nlp_score(d: dict) -> float:
    """
    Score = positive_count * 0.6 + rating * 0.4
    Same formula as product_nlp_score.
    """
    reviews = d.get('reviews', [])
    pos = cached_xlm(tuple(reviews)) if reviews else 7
    return round(pos * 0.6 + d['rating'] * 0.4, 1)

def discounted(p: dict) -> float:
    return round(p['price'] * (1 - p['disc'] / 100), 0)

# ── DEPARTMENTS ────────────────────────────────────────────────────
DEPTS = [
    {'name':'Cardiology',      'icon':'❤️', 'color':'#dc2626'},
    {'name':'Dermatology',     'icon':'✨', 'color':'#db2777'},
    {'name':'Pediatrics',      'icon':'👶', 'color':'#2563eb'},
    {'name':'Orthopedics',     'icon':'🦴', 'color':'#d97706'},
    {'name':'Neurology',       'icon':'🧠', 'color':'#7c3aed'},
    {'name':'Endocrinology',   'icon':'⚗️', 'color':'#059669'},
    {'name':'Gastroenterology','icon':'🫁', 'color':'#0891b2'},
    {'name':'Psychiatry',      'icon':'🧘', 'color':'#0369a1'},
    {'name':'Ophthalmology',   'icon':'👁️', 'color':'#065f46'},
    {'name':'ENT',             'icon':'👂', 'color':'#92400e'},
]

# ── DOCTORS — 5 per department ─────────────────────────────────────
# Some doctors have mixed Hindi/Gujarati/English reviews with negatives
# so NLP can actually differentiate and rank meaningfully within each dept.
DOCTORS = [
    # CARDIOLOGY
    {'id':1,'name':'Priya Sharma','dept':'Cardiology','spec':'Interventional Cardiologist','exp':14,'rating':4.9,'fee':800,'emoji':'👩‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','2:00 PM','3:00 PM','4:00 PM'],'tags':['heart','cardiac','bp','chest'],'reviews':['Best cardiologist in the city very thorough examination','Excellent doctor diagnosed my blockage immediately','Very professional and caring explains everything clearly','My father recovered well under her care highly recommend','Quick diagnosis and right medication no side effects','Stent procedure was very smooth and painless','Regular follow-ups are very detailed and reassuring','Treated my mother for 2 years outstanding results','Very calm and composed even in emergency','Explained everything before procedure very well']},
    {'id':2,'name':'Vikram Nair','dept':'Cardiology','spec':'Cardiac Electrophysiologist','exp':11,'rating':4.7,'fee':900,'emoji':'👨‍⚕️','slots':['8:00 AM','9:00 AM','10:00 AM','2:00 PM','3:00 PM'],'tags':['arrhythmia','pacemaker','heart rhythm'],'reviews':['Fixed my arrhythmia problem perfectly thank you doctor','Very knowledgeable about heart rhythm disorders','Pacemaker procedure went very smoothly under his care','Explained the procedure in very simple language','Good follow-up care after the surgery helped recovery','Ablation was a success no more palpitations','Very patient with all my questions before procedure','ECG interpretation skills are excellent','Changed my medication and symptoms improved greatly','Saved me from unnecessary surgery with correct diagnosis']},
    # Mixed reviews — Hindi/Gujarati negatives, will rank lower in Cardiology
    {'id':3,'name':'Ananya Krishnan','dept':'Cardiology','spec':'Preventive Cardiologist','exp':9,'rating':4.6,'fee':700,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','12:00 PM','3:00 PM','4:00 PM'],'tags':['cholesterol','prevention','lifestyle'],'reviews':['Great advice on diet and lifestyle changes that worked','Very helpful in preventing my heart disease development','બહુ ખરાબ અનુભવ થયો ડૉક્ટર ધ્યાન નથી આપતા','પૈસા બગડ્યા કોઈ ફાયદો ન થયો ખૂબ નિરાશ','Prevented me from needing medication with lifestyle changes','Young doctor but very knowledgeable about prevention','बहुत लंबा इंतजार करना पड़ा और फिर भी कोई हल नहीं बुरा','Very scientific approach to cardiac prevention','पैसे बर्बाद हुए कोई फायदा नहीं हुआ बहुत खराब','Best preventive cardiology consultation I have had']},
    {'id':4,'name':'Suresh Menon','dept':'Cardiology','spec':'Echocardiography Specialist','exp':16,'rating':4.8,'fee':750,'emoji':'👨‍⚕️','slots':['9:00 AM','11:00 AM','2:00 PM','4:00 PM'],'tags':['echo','valve','heart scan'],'reviews':['Best echocardiography specialist I have visited hands down','Accurate diagnosis of my valve problem first time','Very experienced has seen thousands of cases clearly','Reports explained clearly with visual aids shown','Reasonable fees for the outstanding quality of service','Found my mitral valve problem that others missed','Very thorough echo examination takes time to explain','Stress echo was conducted very professionally','Detailed wall motion analysis was very helpful','Would recommend to anyone needing cardiac imaging']},
    {'id':5,'name':'Deepa Iyer','dept':'Cardiology','spec':'Heart Failure Specialist','exp':12,'rating':4.7,'fee':850,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','3:00 PM','4:00 PM','5:00 PM'],'tags':['heart failure','pump','ejection fraction'],'reviews':['Managed my heart failure wonderfully quality of life improved','Quality of life improved significantly after her treatment plan','Very compassionate doctor with great clinical knowledge','Regular monitoring and timely intervention saved my life','Excellent coordination with other specialists when needed','Fluid management protocol she designed is excellent','Device therapy recommendation was absolutely correct','BNP levels came down dramatically with her care','Very clear explanation of heart failure self management','Best heart failure doctor in the region without doubt']},
    # DERMATOLOGY
    {'id':6,'name':'Arjun Mehta','dept':'Dermatology','spec':'Cosmetic & Clinical Dermatologist','exp':10,'rating':4.8,'fee':600,'emoji':'👨‍⚕️','slots':['10:00 AM','11:00 AM','12:00 PM','3:00 PM','4:00 PM'],'tags':['skin','acne','hair','rash'],'reviews':['Acne cleared completely in 3 months amazing results','Best dermatologist for skin problems highly recommend','Hair fall stopped completely after his treatment protocol','Very modern approach with latest treatments and technology','Great results for my hyperpigmentation dark spots gone','Chemical peel results were outstanding very professional','Prescribed isotretinoin carefully with proper monitoring','Post acne scarring treatment gave excellent improvement','Very hygenic clinic and professional staff','Would not go anywhere else for my skin concerns']},
    {'id':7,'name':'Kavitha Rao','dept':'Dermatology','spec':'Trichologist & Hair Specialist','exp':8,'rating':4.7,'fee':550,'emoji':'👩‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','2:00 PM','3:00 PM'],'tags':['hair loss','alopecia','scalp'],'reviews':['My hair regrowth has been absolutely amazing','Best trichologist with very scientific approach to hair','PRP treatment done here gave excellent visible results','Detailed scalp analysis before starting any treatment','Very honest about what treatments will actually work','Diagnosed my DUPA early and started right treatment','Hair transplant referral was excellent and timely','Nutritional deficiency causing hair loss found quickly','Minoxidil protocol and monitoring has been perfect','Very empathetic about hair loss being distressing issue']},
    # Mixed — some negative reviews, will rank lower in Dermatology
    {'id':8,'name':'Rahul Bhat','dept':'Dermatology','spec':'Psoriasis & Eczema Specialist','exp':13,'rating':4.6,'fee':650,'emoji':'👨‍⚕️','slots':['8:00 AM','9:00 AM','10:00 AM','2:00 PM','4:00 PM'],'tags':['psoriasis','eczema','atopic'],'reviews':['Psoriasis under control for first time in years great','સારવાર પછી કોઈ ફરક નથી પડ્યો ખૂબ નિરાશ થઈ','Very up-to-date with the latest treatment guidelines','No major side effects with the treatment plan given','दवाई से कोई फायदा नहीं हुआ पैसे बर्बाद बेकार डॉक्टर','UVB phototherapy protocol designed was very effective','Taught me excellent trigger avoidance strategies','ઘણા મોંઘા ચાર્જ છે ફાયદો ઓછો ખૂબ ખરાબ','Regular monitoring makes me feel very safe on biologics','Best psoriasis doctor I have seen in 10 years of suffering']},
    {'id':9,'name':'Sneha Pillai','dept':'Dermatology','spec':'Aesthetic & Laser Dermatologist','exp':7,'rating':4.9,'fee':800,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM','4:00 PM'],'tags':['laser','botox','anti-aging'],'reviews':['Laser treatment results are truly outstanding incredible','Best aesthetic dermatologist in this entire area without doubt','Very natural looking filler results no frozen face at all','Skin is absolutely glowing after chemical peel session','Very hygienic clinic with absolutely latest equipment','CO2 laser for acne scars gave amazing improvement','Thread lift results were very natural and long lasting','Botox dosing was perfect no frozen look at all','Always does what is actually needed no overselling','Best investment I made in my skin career']},
    {'id':10,'name':'Mohan Das','dept':'Dermatology','spec':'Pediatric Dermatologist','exp':11,'rating':4.7,'fee':500,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','3:00 PM','4:00 PM'],'tags':['child skin','baby rash','pediatric'],'reviews':['Very gentle with my baby daughter made her feel safe','Child friendly approach with no fear or crying at all','Diagnosed my son condition correctly in very first visit','Mother friendly explanations very patient with our questions','Great at managing childhood eczema with gentle approach','Baby atopic dermatitis now well controlled with his regimen','Very good at reassuring anxious parents like me','Molluscum treatment was quick and relatively painless','Excellent at differentiating viral from bacterial skin infections','Would not take my children to any other skin doctor']},
    # NEUROLOGY
    {'id':11,'name':'Kavita Reddy','dept':'Neurology','spec':'Stroke & Epilepsy Specialist','exp':12,'rating':4.8,'fee':1000,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM','4:00 PM'],'tags':['brain','migraine','seizure','stroke'],'reviews':['Migraine completely controlled with her comprehensive protocol','Best neurologist very thorough investigation of all symptoms','Epilepsy seizures reduced by 90 percent significant improvement','Very systematic approach to diagnosis using all evidence','Explains complex MRI reports in very simple terms','Started me on right AED that has no side effects','EEG interpretation and explanation was excellent','Stroke prevention advice has been outstanding and practical','Very quick to respond to medication changes needed','Changed my life with correct epilepsy diagnosis finally']},
    {'id':12,'name':'Anand Gupta','dept':'Neurology','spec':'Movement Disorder Specialist','exp':15,'rating':4.7,'fee':1100,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','2:00 PM','3:00 PM'],'tags':['parkinson','tremor','movement'],'reviews':['Parkinson management dramatically improved my quality of life','Very experienced with deep brain stimulation procedures','Movement tremors reduced significantly after his treatment plan','Very compassionate with elderly patients and their families','Latest treatment protocols are always used in his practice','DBS programming was excellent tremors completely controlled','Levodopa optimization was done very carefully and effectively','Very good at explaining Parkinson progression to family','Always available for urgent calls regarding medication issues','Best Parkinson specialist in the region by far']},
    {'id':13,'name':'Preethi Nair','dept':'Neurology','spec':'Headache & Migraine Specialist','exp':8,'rating':4.9,'fee':900,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','12:00 PM','3:00 PM','4:00 PM'],'tags':['headache','migraine','cluster'],'reviews':['Chronic headache cured after 10 long years of suffering','Best migraine specialist I have ever seen in my life','Botox for chronic migraine worked absolutely brilliantly','Preventive treatment protocol completely changed my entire life','Very scientific systematic approach to headache management','Diagnosed my NDPH when others called it stress headache','Nerve block procedure for cluster headache was very effective','Keeping a headache diary as she advised was very helpful','Topamax dosing was done very gradually no side effects','From 20 headache days to 2 per month remarkable result']},
    # Mixed — negative reviews, ranks lower in Neurology
    {'id':14,'name':'Rajesh Kumar','dept':'Neurology','spec':'Spine & Nerve Specialist','exp':13,'rating':4.6,'fee':950,'emoji':'👨‍⚕️','slots':['8:00 AM','9:00 AM','10:00 AM','2:00 PM','3:00 PM'],'tags':['spine','disc','nerve','sciatica'],'reviews':['Sciatica pain completely gone after nerve block procedure','Avoided major surgery with his conservative management approach','ઘૂંટણ અને કમરનો દુખાવો ઓછો નથી થયો ખૂબ ખરાબ','EMG and NCS results explained very clearly and understandably','बहुत महंगी फीस है और कोई खास फर्क नहीं पड़ा बुरा','L4-L5 disc issue managed without surgery brilliant','दवाई से साइड इफेक्ट हुआ डॉक्टर ने ध्यान नहीं दिया बुरा','Very good at determining which cases actually need surgery','Physiotherapy referral combined with medication worked perfectly','MRI findings explained in language I could actually understand']},
    {'id':15,'name':'Meena Sharma','dept':'Neurology','spec':'Dementia & Memory Specialist','exp':10,'rating':4.7,'fee':850,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM','5:00 PM'],'tags':['dementia','alzheimer','memory'],'reviews':['Mother dementia is now well managed under her care','Very empathetic approach to a very difficult condition','Family counseling sessions were absolutely invaluable help','Latest cognitive assessment tools give clear picture','Great support system provided for caregivers like me','Diagnosed early MCI which allowed us to plan well','Caregiver burnout addressed very sensitively and practically','Cognitive rehabilitation program has helped mother stay engaged','Very clear guidance on legal and financial planning needed','Best doctor we have found for this terrible condition']},
    # OPHTHALMOLOGY
    {'id':16,'name':'Deepa Gupta','dept':'Ophthalmology','spec':'Retina & Cataract Surgeon','exp':14,'rating':4.8,'fee':700,'emoji':'👩‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','2:00 PM','3:00 PM'],'tags':['eye','vision','cataract','retina'],'reviews':['Cataract surgery done with absolutely zero complications excellent','Vision restored to perfect 6/6 after her brilliant surgery','Retinal detachment treated very successfully full vision saved','Very advanced modern equipment in her excellent clinic','LASIK results here are outstanding 5 years still perfect','Vitrectomy procedure was very smooth quick recovery','AMD treatment with injections is expertly managed here','Post cataract care instructions were very clear and detailed','Always explains procedure risks and benefits very clearly','Best eye surgeon I know incredible surgical skill']},
    {'id':17,'name':'Rajiv Sinha','dept':'Ophthalmology','spec':'Glaucoma Specialist','exp':11,'rating':4.7,'fee':650,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','2:00 PM','3:00 PM','4:00 PM'],'tags':['glaucoma','eye pressure','optic nerve'],'reviews':['Glaucoma detected very early and now perfectly well managed','Eye pressure completely controlled with minimal number of drops','Very thorough visual field testing and interpretation skills','Explained glaucoma progression risks very clearly to me','Regular careful monitoring has absolutely preserved my vision','SLT laser procedure was very effective and pain free','Very good at explaining iridotomy procedure beforehand','Trabeculectomy surgery was excellently performed with great result','Optic nerve analysis is extremely thorough every visit','Best glaucoma doctor and prevented me from going blind']},
    {'id':18,'name':'Sunita Khanna','dept':'Ophthalmology','spec':'Cornea & External Eye','exp':9,'rating':4.6,'fee':600,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','12:00 PM','3:00 PM','4:00 PM'],'tags':['cornea','dry eye','contact lens'],'reviews':['Keratoconus treated perfectly with cross-linking procedure here','Dry eye syndrome finally well managed with her guidance','Contact lens fitting advice was the best I have received','Very gentle examination technique makes it comfortable always','Corneal graft coordinated absolutely seamlessly excellent team work','Best corneal topography analysis and explanation I received','Corneal ulcer treated very aggressively and effectively','Eye drop compliance schedule she designed is very practical','Scleral lens fitting was perfect for my dry eye','Best cornea specialist in the city without any doubt']},
    {'id':19,'name':'Karthik Iyer','dept':'Ophthalmology','spec':'Pediatric Ophthalmologist','exp':8,'rating':4.8,'fee':550,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','3:00 PM','4:00 PM'],'tags':['child eye','squint','amblyopia'],'reviews':['Squint surgery on my daughter gave perfect aligned result','Lazy eye amblyopia treatment was very very successful','Very child-friendly playful approach children like him a lot','Vision therapy program for my son is very well designed','Spectacle prescription was very accurate for child first visit','Strabismus diagnosed correctly when local doctor missed it','Patching therapy compliance improved with his encouragement','Very good at explaining to parents what is happening','My child does not cry at all in his clinic','Surgery outcome for squint was absolutely beautiful result']},
    {'id':20,'name':'Madhuri Bose','dept':'Ophthalmology','spec':'Neuro-Ophthalmologist','exp':13,'rating':4.7,'fee':800,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM'],'tags':['optic nerve','visual field','double vision'],'reviews':['Rare optic neuritis was diagnosed correctly here thankfully','Visual field loss has stabilized completely with her treatment','Complex double vision case was solved with correct prism','Excellent coordination with neurology team for my case','Very thorough investigation always done before starting treatment','Idiopathic intracranial hypertension managed perfectly here','Lumbar puncture was done very smoothly and professionally','Explained papilloedema significance very clearly to me','Thyroid eye disease treatment was very comprehensive good','Best specialist at the intersection of eye and brain']},
    # PSYCHIATRY
    {'id':21,'name':'Suresh Nair','dept':'Psychiatry','spec':'Anxiety & Depression Specialist','exp':9,'rating':4.7,'fee':600,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','4:00 PM','5:00 PM'],'tags':['anxiety','depression','stress','OCD'],'reviews':['Depression finally under complete control after his therapy','Very non-judgmental and deeply compassionate approach always','CBT sessions have completely changed my negative thinking patterns','Absolutely no stigma or judgment in this clinic at all','Medication adjustments were done very carefully and thoughtfully','Recovered from severe depression in just 3 months amazing','OCD treatment with ERP therapy was excellently conducted','Very good at explaining the science behind mental illness','SSRI dosing was gradual and side effects were minimal','Changed my entire perspective on mental health treatment']},
    {'id':22,'name':'Nisha Patel','dept':'Psychiatry','spec':'Child & Adolescent Psychiatrist','exp':8,'rating':4.8,'fee':700,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM','4:00 PM'],'tags':['ADHD','autism','child mental health'],'reviews':['Son ADHD is now managed absolutely beautifully excellent','Autism spectrum assessment was extremely thorough and detailed','Very patient with difficult child behaviors during sessions','Family therapy sessions have been incredibly helpful for us','School performance has improved so dramatically since starting','ADHD medication dosing was done very carefully step by step','Behavioral intervention plan she designed works very well','Social skills group she recommended was very beneficial','Very good at helping parents understand child needs','Best child psychiatrist for developmental conditions in city']},
    # Mixed — negative reviews in Hindi/Gujarati, ranks lower
    {'id':23,'name':'Deepak Mishra','dept':'Psychiatry','spec':'Addiction Specialist','exp':12,'rating':4.6,'fee':650,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','2:00 PM','3:00 PM'],'tags':['addiction','alcohol','de-addiction'],'reviews':['Brother has recovered from alcohol addiction here truly amazing','Very structured comprehensive de-addiction program they follow','ડૉ. સાથે વાત કરવી ખૂબ અઘરી હતી ઓછો સમય આપ્યો ખૂબ ખરાબ','Relapse prevention strategies he taught are very effective','इलाज से कोई फायदा नहीं हुआ पैसे बर्बाद बेकार डॉक्टर','Family therapy component of his program was invaluable','Motivational interviewing approach made brother want to change','बहुत बुरा अनुभव डॉक्टर ने ध्यान नहीं दिया और पैसे लिए','12 step program integration with medical treatment works','Two years sober now thanks to this excellent doctor']},
    {'id':24,'name':'Priya Menon','dept':'Psychiatry','spec':'Sleep Disorder Specialist','exp':7,'rating':4.7,'fee':550,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','3:00 PM','4:00 PM','5:00 PM'],'tags':['sleep','insomnia','sleep apnea'],'reviews':['Insomnia was completely cured without any heavy medication','Sleep hygiene advice she gave was absolutely excellent practical','CBT for insomnia was incredibly effective no sleeping pills','Sleep study was conducted very professionally good report','10 years of terrible sleep problems solved in only 2 months','CPAP titration for sleep apnea was excellently managed','Diagnosed my restless legs syndrome correctly when others missed','Sleep diary analysis was very detailed and informative','Light therapy timing advice dramatically improved my sleep','Best sleep doctor completely changed my quality of life']},
    {'id':25,'name':'Amit Sharma','dept':'Psychiatry','spec':'Trauma & PTSD Specialist','exp':10,'rating':4.8,'fee':700,'emoji':'👨‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM'],'tags':['trauma','PTSD','grief'],'reviews':['PTSD from terrible accident finally treated very effectively','EMDR therapy worked absolute wonders for my trauma','Very safe completely confidential and non-judgmental environment','Trauma processing sessions were deeply healing thank you doctor','Referred me to support groups which have helped greatly','Prolonged exposure therapy was well paced and effective','Complex PTSD from childhood correctly diagnosed and treated','Somatic therapy component was very innovative and helpful','Flashbacks and nightmares reduced by 90 percent remarkable','Best trauma specialist helped me reclaim my entire life']},
    # ENT
    # Mixed — negative reviews, ranks lower in ENT
    {'id':26,'name':'Rajan Pillai','dept':'ENT','spec':'Head & Neck Surgeon','exp':11,'rating':4.6,'fee':550,'emoji':'👨‍⚕️','slots':['8:00 AM','9:00 AM','10:00 AM','3:00 PM','4:00 PM'],'tags':['ear','nose','throat','sinus'],'reviews':['Sinus surgery done very professionally excellent result','Hearing aid fitting advice was absolutely excellent helpful','ઓપરેશન પછી ઘણી તકલીફ થઈ ડૉ. ઉપલબ્ધ ન હતા ખૂબ ખરાબ','Very experienced surgeon with consistently good patient outcomes','Post operative care instructions were very clear and detailed','सर्जरी के बाद बहुत दर्द था और डॉक्टर मिले नहीं बुरा','Voice change after thyroid surgery was avoided skillfully','ફોલો-અપ માટે ઘણો સમય વેઈટ કરવો પડ્યો ખૂબ ખરાબ સેવા','Parotid surgery was done with excellent facial nerve preservation','Best ENT surgeon in the region very highly skilled']},
    {'id':27,'name':'Shilpa Verma','dept':'ENT','spec':'Cochlear Implant Specialist','exp':9,'rating':4.8,'fee':800,'emoji':'👩‍⚕️','slots':['10:00 AM','11:00 AM','2:00 PM','3:00 PM'],'tags':['cochlear','deaf','hearing loss'],'reviews':['Cochlear implant has completely changed my daughters entire life','Hearing was mapped absolutely perfectly under her expert guidance','Very patient in teaching hearing rehabilitation exercises to family','Excellent post-implant therapy coordination with rehab team','Best decision we ever made was to come here for CI','Programming sessions for cochlear implant have been excellent','Audiological assessment before implant was very comprehensive','Helped family understand realistic expectations from CI very well','Follow-up care after surgery has been outstanding consistent','Two years post implant daughter now speaks clearly excellent']},
    {'id':28,'name':'Arvind Shah','dept':'ENT','spec':'Voice & Throat Specialist','exp':10,'rating':4.7,'fee':600,'emoji':'👨‍⚕️','slots':['9:00 AM','10:00 AM','11:00 AM','3:00 PM','4:00 PM'],'tags':['voice','larynx','swallowing','singer'],'reviews':['Voice disorder was treated completely without any surgery','Professional singer nodule was managed very conservatively well','Stroboscopy voice analysis was extremely detailed and helpful','Thyroid surgery done here with perfect voice preservation','Speech therapy referral after laryngeal surgery was very helpful','Dysphagia evaluation and treatment was very comprehensive good','Laryngeal cancer screening was very thorough and reassuring','Professional singers receive very specialized care here excellent','Voice rest and steam therapy advice was very practical','Microlaryngoscopy procedure was done with excellent surgical skill']},
    {'id':29,'name':'Pooja Jain','dept':'ENT','spec':'Rhinologist & Allergy','exp':8,'rating':4.7,'fee':500,'emoji':'👩‍⚕️','slots':['9:00 AM','10:00 AM','12:00 PM','3:00 PM','4:00 PM'],'tags':['allergy','rhinitis','sinusitis','polyp'],'reviews':['Chronic sinusitis was finally completely and properly cured','Nasal polyp surgery was very successfully done excellent','Allergy skin testing was done very comprehensively thorough','Immunotherapy she prescribed is working very well so far','Breathing has improved so dramatically after treatment amazing','Septoplasty for deviated septum was excellently performed','Nasal endoscopy was done very skillfully minimal discomfort','Smell loss after COVID treated successfully here great','Allergic rhinitis now controlled without daily antihistamines','Best nose and allergy specialist I have consulted']},
]

# ── PRODUCTS ───────────────────────────────────────────────────────
_U = 'https://images.unsplash.com/photo-'
PRODUCTS = [
    # PAIN RELIEF
    {'id':1,'name':'Paracetamol 500mg','cat':'Pain Relief','mfr':'Cipla','price':45,'disc':0,'stock':500,'rating':4.8,'rx':False,'img':f'{_U}1584308666744-24d5c474f2ae?w=300&q=80','tags':'pain fever headache paracetamol analgesic','reviews':['Works in 20 minutes excellent relief','Best pain reliever very safe effective','No side effects use regularly perfect','Effective for fever in children great','Trusted brand Cipla top quality','Fast relief from body ache brilliant','Affordable and easily available good','Doctor recommended works perfectly','Very safe even with regular use','Carry everywhere I travel essential']},
    {'id':2,'name':'Ibuprofen 400mg','cat':'Pain Relief','mfr':'Abbott','price':55,'disc':5,'stock':380,'rating':4.5,'rx':False,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'pain ibuprofen anti-inflammatory nsaid','reviews':['Better than paracetamol for joint pain','Reduces swelling within hours amazing','Works well for dental pain excellent','Good for menstrual cramps helpful','Anti-inflammatory effect very noticeable','Lasts longer than paracetamol good','Effective for sports injuries perfect','Take with food to avoid stomach','Recommend for arthritis pain works','Very good value for money']},
    # Mixed negative reviews — will rank lower in Pain Relief
    {'id':3,'name':'Diclofenac Gel 30g','cat':'Pain Relief','mfr':'Novartis','price':65,'disc':0,'stock':280,'rating':4.4,'rx':False,'img':f'{_U}1583947215259-38e31be8751f?w=300&q=80','tags':'diclofenac gel topical joint pain arthritis','reviews':['Best topical for back pain relief','Knee pain significantly reduced great','ઘૂંટણ પર લગાવ્યા પછી કોઈ ફરક ન પડ્યો બેકાર પ્રોડક્ટ','Doctor recommended this product works','कोई असर नहीं हुआ पैसे बर्बाद बहुत खराब प्रोडक्ट','Long lasting local pain relief','Post surgery pain management good','ત્વચા પર ખૂજલી થઈ ગઈ ખૂબ ખરાબ','No stomach issues unlike oral NSAIDs','Absorbed quickly and works fast']},
    {'id':4,'name':'Combiflam Tablet','cat':'Pain Relief','mfr':'Sanofi','price':40,'disc':0,'stock':600,'rating':4.7,'rx':False,'img':f'{_U}1587854692152-cbe660dbde88?w=300&q=80','tags':'combiflam ibuprofen paracetamol combination pain','reviews':['Double action formula brilliant effective','One tablet handles pain and fever','Very popular in my family always','Dentist recommended for tooth pain works','Great for cold related body pain','Good value for combination product','No side effects in long use','Faster than single ingredient tablets','Trusted brand for 20 years excellent','Very effective combination medicine']},
    {'id':5,'name':'Aspirin 75mg Cardiac','cat':'Pain Relief','mfr':'Bayer','price':30,'disc':0,'stock':700,'rating':4.6,'rx':False,'img':f'{_U}1471864190281-a93a3070b6de?w=300&q=80','tags':'aspirin cardiac blood thinner platelet prevention','reviews':['Cardiologist prescribed for prevention works','Daily for heart protection very good','Very affordable cardiac medication excellent','No issues daily use 5 years great','Enteric coated gentle on stomach','Blood thinning effect proven reliable','Essential for post stent patients vital','Doctor approved cardiac aspirin works','Very effective preventive medication important','Generic version equally effective good']},
    # Mixed negative reviews, ranks lower in Pain Relief
    {'id':6,'name':'Tramadol 50mg','cat':'Pain Relief','mfr':'Sun Pharma','price':85,'disc':0,'stock':100,'rating':4.2,'rx':True,'img':f'{_U}1584308666744-24d5c474f2ae?w=300&q=80','tags':'tramadol pain severe chronic opioid','reviews':['Works for severe pain when others fail','Doctor prescribed carefully monitored safe','ઘણી ગંભીર side effect થઈ ખૂબ ખરાબ અનુભવ','Take exactly as prescribed important','बहुत बुरा side effect हुआ उल्टी और चक्कर आए','Specialist prescribed only medication correct','ઉલ્ટી અને ચક્કર આવ્યા ખૂબ ખરાબ','बहुत ज्यादा नींद आती है काम नहीं कर पाते बुरा','Follow prescription strictly very important','Under medical supervision this works well']},
    # VITAMINS
    {'id':7,'name':'Vitamin D3 60K IU','cat':'Vitamins','mfr':'Sun Pharma','price':180,'disc':10,'stock':300,'rating':4.7,'rx':False,'img':f'{_U}1604881988758-f76ad2f7aac1?w=300&q=80','tags':'vitamin d3 bones immunity supplement','reviews':['Deficiency corrected in 2 months great','Bone pain reduced significantly excellent','Weekly dose very convenient good','Sun Pharma quality reliable trusted','Energy levels improved dramatically amazing','Doctor prescribed works as expected','Calcium absorption improved noticeably','Mood and immunity both improved','Very cost effective supplement excellent','Must have for Indian population']},
    {'id':8,'name':'Vitamin C 1000mg','cat':'Vitamins','mfr':'HealthKart','price':320,'disc':20,'stock':450,'rating':4.7,'rx':False,'img':f'{_U}1625708458528-802ec79b1ed8?w=300&q=80','tags':'vitamin c immunity supplement ascorbic','reviews':['Immunity improved significantly wonderful','Cold and flu frequency reduced excellent','Good absorption with zinc very effective','Antioxidant benefit clearly visible great','Skin glow improved after 1 month','Very gentle on stomach perfect','Exercise recovery improved noticeably good','HealthKart quality always reliable excellent','Great value for bulk purchase','Effervescent variety tastes good too']},
    # Mixed negative reviews, ranks lower in Vitamins
    {'id':9,'name':'Vitamin B Complex','cat':'Vitamins','mfr':'Mankind','price':95,'disc':0,'stock':400,'rating':4.5,'rx':False,'img':f'{_U}1631549916768-4119b4220292?w=300&q=80','tags':'vitamin b energy nerve health b12','reviews':['Energy levels back to normal great','Nerve pain in hands reduced excellent','ટેબ્લેટ ગળ્યા પછી ઉલ્ટી જેવું થયું ખૂબ ખરાબ','Vegetarian friendly formulation perfect','इससे कोई फायदा नहीं हुआ पैसे बर्बाद बेकार दवाई','Hair and nail growth improved good','Very affordable B complex excellent','Doctor approved for pregnancy safe','Good absorption with meal helpful','Neuropathy symptoms reduced noticeably']},
    {'id':10,'name':'Fish Oil Omega-3','cat':'Vitamins','mfr':'Himalaya','price':480,'disc':15,'stock':280,'rating':4.6,'rx':False,'img':f'{_U}1512069772995-ec65ed45afd6?w=300&q=80','tags':'omega3 fish oil heart brain supplement','reviews':['Triglycerides came down with use excellent','Brain function improved noticeably great','Joint lubrication noticed after 2 months','Himalaya quality always trustworthy good','No fishy burps with enteric coating','Cardiologist approved heart health benefit','Anti-inflammatory effect visible excellent','Good DHA content for brain health','Daily use no side effects safe','Very good supplement for heart']},
    {'id':11,'name':'Multivitamin Complete','cat':'Vitamins','mfr':'GNC','price':450,'disc':15,'stock':200,'rating':4.6,'rx':False,'img':f'{_U}1571772996211-2f02c9727629?w=300&q=80','tags':'multivitamin complete nutrition supplement daily','reviews':['All in one convenience is great','GNC quality always premium excellent','Expensive but worth every rupee','Energy and immunity both improved','Sports recovery significantly faster good','Doctor approved for daily use safe','No stomach issues even empty stomach','21 vitamins in one pill convenient','Good for restricted diet excellent','Vegetarian capsule is big plus']},
    {'id':12,'name':'Folic Acid 5mg','cat':'Vitamins','mfr':'Cipla','price':35,'disc':0,'stock':600,'rating':4.8,'rx':False,'img':f'{_U}1604881988758-f76ad2f7aac1?w=300&q=80','tags':'folic acid pregnancy neural tube folate','reviews':['Gynecologist prescribed for pregnancy excellent','Neural tube defect prevention essential vital','Very affordable life saving supplement great','Good bioavailability at this dose','Anemia improved with iron combination','Essential for all pregnant women important','No side effects at standard dose safe','Birth defect risk greatly reduced excellent','Doctor strongly recommended this product','Reliable Cipla formulation trusted brand']},
    # DIABETES
    {'id':13,'name':'Metformin 500mg','cat':'Diabetes','mfr':'USV','price':60,'disc':0,'stock':350,'rating':4.7,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'diabetes sugar glucose metformin insulin','reviews':['Sugar levels well controlled excellent','First line diabetes drug very effective','Weight loss side effect is bonus good','Affordable generic always available excellent','Works better with diet control true','HbA1c improved significantly wonderful','20 year safety track record trusted','Kidney protection benefit proven excellent','Doctor prescribed for prediabetes works','Very well tolerated medication good']},
    {'id':14,'name':'Glucometer Kit','cat':'Diabetes','mfr':'Accu-Chek','price':1200,'disc':12,'stock':95,'rating':4.8,'rx':False,'img':f'{_U}1498837167922-ddd27525d352?w=300&q=80','tags':'glucose glucometer diabetes test kit monitor','reviews':['Accu-Chek accuracy unmatched excellent','Result in 5 seconds very fast great','No calibration needed convenient perfect','Memory stores 500 readings useful','App integration works perfectly great','Lancets cause minimal pain excellent','Doctor approved device brand trusted','Best glucometer for daily monitoring','Bluetooth sync is great feature good','Value for money excellent product']},
    {'id':15,'name':'Insulin Glargine','cat':'Diabetes','mfr':'Sanofi','price':850,'disc':0,'stock':60,'rating':4.9,'rx':True,'img':f'{_U}1559076162-ac1d4a3c0a0b?w=300&q=80','tags':'insulin diabetes type1 glargine basal','reviews':['Basal insulin coverage excellent perfect','Once daily injection very convenient good','Blood sugar control improved dramatically','No major hypoglycemia episodes safe','Type 1 management became much easier','Sanofi quality and cold chain maintained','Pen device very user friendly great','Significantly reduced fasting sugar excellent','Life changing medication for T1D vital','Doctor carefully titrated dose safe']},
    {'id':16,'name':'Jardiance 10mg','cat':'Diabetes','mfr':'Boehringer','price':1800,'disc':5,'stock':80,'rating':4.7,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'jardiance empagliflozin SGLT2 diabetes heart','reviews':['Heart protection benefit exceptional excellent','Weight loss without dieting bonus great','Blood pressure also improved wonderful','Kidney protection proven in trials excellent','Cardiologist added for heart failure good','HbA1c down by 1.5% in 3 months','Combination with metformin works great','Very well tolerated medication good','Insurance covers expensive but worth it','Recommended by both doctor and cardiologist']},
    {'id':17,'name':'CGM FreeStyle Libre','cat':'Diabetes','mfr':'Abbott','price':2800,'disc':8,'stock':40,'rating':4.8,'rx':False,'img':f'{_U}1498837167922-ddd27525d352?w=300&q=80','tags':'CGM continuous glucose monitoring freestyle sensor','reviews':['Game changer for diabetes management excellent','No finger pricks required is amazing wonderful','App data helps doctor optimize treatment','14 day sensor life good value great','Alarms for high and low are lifesaving vital','Understanding glucose patterns changed my life','Easy application even self applied good','Water resistant and very durable excellent','Highly recommend for all T1D patients','Best diabetes monitoring technology available']},
    # Mixed negative reviews, ranks lower in Diabetes
    {'id':18,'name':'Sitagliptin 100mg','cat':'Diabetes','mfr':'MSD','price':320,'disc':0,'stock':150,'rating':4.5,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'sitagliptin DPP4 diabetes sugar HbA1c','reviews':['Very safe with minimal side effects good','Good add-on to metformin excellent','No weight gain unlike other diabetes drugs','Kidney dose adjustment simple and practical','ખૂબ મોંઘી દવા છે ફાયદો ઓછો નિરાશ','Tolerability is excellent no issues','HbA1c reduction consistent reliable','शुगर level में कोई खास सुधार नहीं हुआ बेकार दवा','Good option for kidney issues patients','Januvia quality and reliability trusted']},
    # DEVICES
    {'id':19,'name':'BP Monitor Omron','cat':'Devices','mfr':'Omron','price':1850,'disc':15,'stock':80,'rating':4.9,'rx':False,'img':f'{_U}1615461066841-6116e61058f4?w=300&q=80','tags':'blood pressure monitor bp digital omron','reviews':['Clinically validated accuracy proven excellent','Bluetooth app works flawlessly great','Easy one touch operation perfect','Large display for elderly parents good','Memory for 2 users convenient feature','Doctor grade accuracy at home excellent','Validated for hypertension monitoring good','Irregular heartbeat detection bonus great','USB charging very convenient modern','Omron brand trusted by cardiologists']},
    {'id':20,'name':'Pulse Oximeter','cat':'Devices','mfr':'Dr Trust','price':950,'disc':10,'stock':120,'rating':4.8,'rx':False,'img':f'{_U}1584362917165-526a968579e8?w=300&q=80','tags':'oxygen spo2 oximeter pulse device','reviews':['Accurate SpO2 readings consistently excellent','Result in under 10 seconds perfect','Very affordable for home monitoring good','Display bright even in sunlight great','Battery life is excellent long lasting','Good for COPD and asthma monitoring','Perfusion index shown is bonus feature','Sleep monitoring useful feature great','Pediatric finger size works child good','Very reliable device excellent quality']},
    {'id':21,'name':'Thermometer Infrared','cat':'Devices','mfr':'Microtek','price':380,'disc':5,'stock':200,'rating':4.7,'rx':False,'img':f'{_U}1584308666744-24d5c474f2ae?w=300&q=80','tags':'thermometer temperature fever digital infrared','reviews':['Non-contact very hygienic excellent feature','Result in 1 second instant fast perfect','Very accurate compared to mercury type','Good for young children who resist','Fever alarm feature helpful practical','Easy to calibrate and use great','Memory stores last 20 readings useful','Very affordable and reliable product','Object temperature mode also useful good','Highly recommend for every home']},
    # Mixed negative reviews, ranks lower in Devices
    {'id':22,'name':'Nebulizer Machine','cat':'Devices','mfr':'Omron','price':1200,'disc':10,'stock':150,'rating':4.7,'rx':False,'img':f'{_U}1615461066841-6116e61058f4?w=300&q=80','tags':'nebulizer asthma breathing respiratory treatment','reviews':['Asthma attacks managed at home excellent','Very quiet operation unlike old models','Fine mist excellent for lungs delivery','Child friendly design reduces fear good','ત્રણ મહિનામાં મોટર બળી ગઈ ખૂબ ખરાબ ક્વોલિટી','Medication delivery very efficient perfect','Easy cleaning after each use practical','एक महीने में खराब हो गया बहुत बुरी quality waste of money','Doctors recommend Omron nebulizer trusted','Reduced hospital visits significantly excellent']},
    {'id':23,'name':'Digital Stethoscope','cat':'Devices','mfr':'Littmann','price':4500,'disc':0,'stock':25,'rating':4.9,'rx':False,'img':f'{_U}1530026405186-ed1f139313f3?w=300&q=80','tags':'stethoscope digital doctor medical examination','reviews':['Sound amplification is outstanding excellent','Bluetooth recording for doctor sharing great','Medical grade quality for home use good','Investment lasting 20 years worth every rupee','Littmann is the gold standard brand trusted','App analysis of heart sounds useful feature','Heart sounds very clear and audible perfect','Premium product justified price excellent','Doctors always recommend Littmann brand','Tunable diaphragm technology is brilliant']},
    # SKINCARE
    {'id':24,'name':'CeraVe Moisturizing Cream','cat':'Skincare','mfr':'CeraVe','price':680,'disc':8,'stock':200,'rating':4.9,'rx':False,'img':f'{_U}1556228720-195a672e8a03?w=300&q=80','tags':'moisturizer dry skin ceramide dermatology CeraVe','reviews':['Dermatologist recommended and approved excellent','Eczema greatly improved with daily use wonderful','Non-greasy formula very comfortable perfect','Ceramide technology scientifically proven effective','Fragrance free good for sensitive skin great','Very gentle even for baby skin safe','Absorption excellent within minutes good','Long lasting moisture for 24 hours excellent','Best moisturizer period full stop','Post procedure skin care excellent choice']},
    {'id':25,'name':'SPF50+ Sunscreen PA++++','cat':'Skincare','mfr':'Neutrogena','price':520,'disc':12,'stock':280,'rating':4.7,'rx':False,'img':f'{_U}1556228578-8c89e6adf883?w=300&q=80','tags':'sunscreen SPF sun protection UV melanin','reviews':['PA++++ protection excellent for India','No white cast which others give great','Water resistant formula for outdoors perfect','Dermatologist recommended for dark spots excellent','Light texture under makeup works well','Tanning completely stopped with regular use','Fragrance free no irritation good','Gentle enough for daily use safe','Acne-prone friendly formula is plus great','Reapplication every 2 hours protocol works']},
    {'id':26,'name':'Niacinamide 10% Serum','cat':'Skincare','mfr':'The Ordinary','price':380,'disc':5,'stock':320,'rating':4.8,'rx':False,'img':f'{_U}1571781926291-c477ebfd024b?w=300&q=80','tags':'niacinamide pore serum zinc brightening skin','reviews':['Pores visibly minimized in 3 weeks excellent','Oil production reduced significantly great','Hyperpigmentation fading wonderful result','Lightweight non-sticky formula perfect','Dermatologist approved ingredient trusted','Works well layered with moisturizer good','Zinc combination anti-acne benefit great','Redness and blemishes reduced excellent','Most cost effective actives product','No irritation unlike retinol products safe']},
    # Mixed negative reviews, ranks lower in Skincare
    {'id':27,'name':'Vitamin C Brightening Serum','cat':'Skincare','mfr':'Mamaearth','price':445,'disc':10,'stock':260,'rating':4.6,'rx':False,'img':f'{_U}1556228720-195a672e8a03?w=300&q=80','tags':'vitamin c serum brightening glow skin','reviews':['Skin brightening visible in 2 weeks excellent','Dark spots fading consistently great result','ચહેરા પર રેડ ફોલ્લા આવ્યા ખૂબ ખરાબ પ્રોડક્ટ','Morning with sunscreen works perfectly','इससे चेहरे पर जलन हुई बहुत बुरा प्रोडक्ट waste','Indian brand with good ingredients trusted','Ferulic acid combination smart formulation','ત્વચા ખૂબ ડ્રાય થઈ ગઈ ફાયદો ઓછો નિરાશ','No breakouts sensitive skin safe','Affordable compared to imported serums']},
    {'id':28,'name':'Salicylic Acid Cleanser','cat':'Skincare','mfr':'La Roche-Posay','price':580,'disc':0,'stock':180,'rating':4.7,'rx':False,'img':f'{_U}1556760544-74068565f05c?w=300&q=80','tags':'salicylic acid cleanser acne BHA face wash','reviews':['Acne breakouts reduced by 70% amazing','Pores look much cleaner after use excellent','BHA exfoliation without over drying perfect','Dermatologist prescribed this brand trusted','French pharmacy quality excellent product','Gentle enough for daily use safe','Blackheads reducing consistently great','Good for oily combination skin excellent','Non-comedogenic formula tested certified','Works best with niacinamide serum together']},
    {'id':29,'name':'Adapalene 0.1% Gel','cat':'Skincare','mfr':'Galderma','price':320,'disc':0,'stock':150,'rating':4.8,'rx':True,'img':f'{_U}1556760544-74068565f05c?w=300&q=80','tags':'adapalene retinoid acne gel anti-aging differin','reviews':['Gold standard for acne treatment excellent','Skin texture dramatically improved in 3 months','Anti-aging benefit is wonderful bonus','Start slowly to avoid irritation wise','Dermatologist prescribed and monitored safe','Better than benzoyl peroxide long term','Generic works equally well affordable','Purging phase expected and temporary normal','Morning moisturizer and sunscreen essential important','Best retinoid for beginners to actives']},
    # CARDIAC
    {'id':30,'name':'Atorvastatin 10mg','cat':'Cardiac','mfr':'Torrent','price':120,'disc':8,'stock':200,'rating':4.6,'rx':True,'img':f'{_U}1587854692152-cbe660dbde88?w=300&q=80','tags':'cholesterol cardiac heart statin atorvastatin','reviews':['Cholesterol normalized in 3 months excellent','Statin therapy very well tolerated good','Cardiologist prescribed no side effects safe','LDL reduced by 50% incredible result','Combined with diet change excellent','Night dose as prescribed works better','Muscle pain possible monitor carefully important','Very affordable generic available great','Post angioplasty essential medication vital','Liver function normal on monitoring safe']},
    # BABY CARE
    {'id':31,'name':'Baby Rash Cream','cat':'Baby Care','mfr':'Johnsons','price':180,'disc':5,'stock':400,'rating':4.7,'rx':False,'img':f'{_U}1556228720-195a672e8a03?w=300&q=80','tags':'baby rash diaper cream infant pediatric zinc','reviews':['Diaper rash cleared overnight amazing','Best baby rash cream no doubt excellent','Pediatrician recommended brand trusted','Zinc oxide formula very effective great','Very gentle on sensitive baby skin safe','Apply each diaper change works perfectly','Trusted brand for 30 years reliable','Affordable for regular use good value','No staining on baby clothes great','Fragrance free version also available']},
    # ANTIBIOTIC
    {'id':32,'name':'Azithromycin 500mg','cat':'Antibiotic','mfr':'Cipla','price':145,'disc':0,'stock':180,'rating':4.5,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'antibiotic infection bacterial azithromycin','reviews':['3 day course convenient effective perfect','Respiratory infection cleared fast excellent','Doctor prescribed for right indication important','Good option for penicillin allergy safe','Mild stomach upset manageable minor','Broad spectrum coverage useful great','Genuine Cipla quality assured trusted','Skin infection treated successfully good','Follow prescription exactly as directed vital','Very effective for most infections']},
    # SUPPLEMENTS
    {'id':33,'name':'Ashwagandha KSM-66 600mg','cat':'Supplements','mfr':'Himalaya','price':350,'disc':5,'stock':280,'rating':4.7,'rx':False,'img':f'{_U}1571772996211-2f02c9727629?w=300&q=80','tags':'ashwagandha adaptogen stress cortisol supplement','reviews':['Stress levels reduced noticeably great','Sleep quality dramatically improved excellent','KSM-66 gold standard extract trusted','Anxiety reduced without medication wonderful','Exercise performance improved measurably good','6 weeks to see full benefits patient','No side effects at recommended dose safe','Immunity and vitality both improved excellent','Himalaya quality always reliable trusted','Best ashwagandha supplement available']},
    {'id':34,'name':'Probiotics 50 Billion CFU','cat':'Supplements','mfr':'Culturelle','price':620,'disc':5,'stock':120,'rating':4.7,'rx':False,'img':f'{_U}1604881988758-f76ad2f7aac1?w=300&q=80','tags':'probiotics gut health lactobacillus IBS digestion','reviews':['IBS symptoms greatly reduced excellent','Digestion improved significantly wonderful','Antibiotic recovery much faster great','Bloating and gas eliminated good','Multiple strain formula more effective excellent','Gastroenterologist approved trusted brand','Refrigeration not required convenient good','Skin also improved with gut health','Immunity benefits noticed winter season good','Consistent daily use gives best results']},
]


PRODUCTS = PRODUCTS + [
    {'id':35,'name':'Metoprolol 25mg','cat':'Cardiac','mfr':'Sun Pharma','price':85,'disc':0,'stock':220,'rating':4.6,'rx':True,'img':f'{_U}1587854692152-cbe660dbde88?w=300&q=80','tags':'metoprolol beta blocker heart cardiac','reviews':['Cardiologist prescribed and heart rate controlled perfectly','No side effects in 2 years wonderful','Effective beta blocker for hypertension','Good for reducing palpitations doctor recommended','Heart rate came down to normal range great','Generic version equally effective as brand','Affordable important cardiac medication available','Follow up echo showed improvement significant','Trustworthy Sun Pharma quality always reliable','Daily medication never missed excellent discipline']},
    {'id':36,'name':'Clopidogrel 75mg','cat':'Cardiac','mfr':'Dr Reddys','price':65,'disc':0,'stock':180,'rating':4.7,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'clopidogrel antiplatelet stent cardiac blood','reviews':['Cardiologist prescribed after stent procedure essential','Blood thinner working as expected no issues','No bleeding side effects on proper dose safe','Very important medication for post stent patients','Dr Reddys quality is excellent reliable brand','Combined with aspirin as prescribed by doctor','Regular monitoring as advised by specialist safe','Peace of mind having this medication daily','Affordable compared to branded version excellent','Never missed a dose highly disciplined patient']},
    {'id':37,'name':'Furosemide 40mg','cat':'Cardiac','mfr':'Cipla','price':25,'disc':0,'stock':300,'rating':4.5,'rx':True,'img':f'{_U}1471864190281-a93a3070b6de?w=300&q=80','tags':'furosemide diuretic water tablet heart failure','reviews':['Leg swelling completely resolved with this medication','Heart failure symptoms much better under control','Morning dose as prescribed works throughout day','Potassium monitored as advised safe','Very affordable important heart failure medication','Breathlessness reduced significantly after starting','Cipla quality excellent and always available','Doctor titrated dose carefully no side effects','Weight reduced with fluid removal excellent result','Essential for managing fluid in heart failure']},
    {'id':38,'name':'Amlodipine 5mg','cat':'Cardiac','mfr':'Pfizer','price':45,'disc':0,'stock':350,'rating':4.6,'rx':True,'img':f'{_U}1587854692152-cbe660dbde88?w=300&q=80','tags':'amlodipine calcium channel blocker blood pressure','reviews':['Blood pressure excellently controlled for 3 years','Ankle swelling mild but manageable tolerable','No major side effects on current dose good','Pfizer quality always reliable and consistent','Combined with other BP medication works well','Morning dose routine easy to remember great','Heart rate also slightly reduced beneficial','Very affordable easily available at pharmacy','Doctor satisfied with BP readings excellent','Safe long term use proven track record']},
    # Mixed negative reviews, ranks lower in Cardiac
    {'id':39,'name':'Rosuvastatin 10mg','cat':'Cardiac','mfr':'AstraZeneca','price':95,'disc':5,'stock':190,'rating':4.7,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'rosuvastatin statin cholesterol LDL cardiac','reviews':['LDL came down from 180 to 90 amazing result','Better tolerated than atorvastatin for me','No muscle pain which I had with previous statin','AstraZeneca quality premium highly reliable brand','સ્નાયુઓમાં ખૂબ દુખાવો થયો ડૉ.એ ચેતવ્યા ન હતા ખૂબ ખરાબ','Very effective at reducing bad cholesterol quickly','Liver function tests all normal on monitoring','मांसपेशियों में बहुत दर्द हुआ बहुत बुरा side effect','Combined with lifestyle change excellent results','Best statin for high risk cardiac patients']},
    {'id':40,'name':'Amoxicillin 500mg','cat':'Antibiotic','mfr':'GSK','price':95,'disc':0,'stock':250,'rating':4.6,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'amoxicillin penicillin bacterial infection throat','reviews':['Throat infection completely cleared in 3 days','Doctor prescribed for right indication important','GSK quality reliable brand trusted by doctors','Good for dental infections works very quickly','No major side effects except mild stomach upset','Complete the full course as prescribed essential','Effective for ear infections in children good','Affordable first line antibiotic widely available','Strep throat resolved completely with 5 day course','Bacterial infection gone completely no recurrence']},
    {'id':41,'name':'Ciprofloxacin 500mg','cat':'Antibiotic','mfr':'Bayer','price':120,'disc':0,'stock':180,'rating':4.5,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'ciprofloxacin fluoroquinolone UTI antibiotic','reviews':['UTI completely resolved in 3 days excellent','Works very fast for urinary tract infections','Doctor prescribed for food poisoning effective','Bayer quality excellent trusted reliable brand','Take with plenty of water as advised important','Avoid sunlight while on medication noted','Culture sensitivity confirmed right choice','Complete the course even after feeling better','Effective for resistant bacteria when needed','Good broad spectrum coverage for infections']},
    {'id':42,'name':'Doxycycline 100mg','cat':'Antibiotic','mfr':'Cipla','price':140,'disc':0,'stock':150,'rating':4.5,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'doxycycline tetracycline antibiotic acne infection','reviews':['Acne significantly improved after 6 weeks excellent','Malaria prophylaxis worked for my travel abroad','Doctor prescribed for respiratory infection effective','Take with food and water to prevent nausea','Avoid lying down for 30 min after taking','Sun sensitivity noted used sunscreen properly','Cipla quality is good and affordable excellent','Complete the course as prescribed by doctor','Very effective for atypical pneumonia tolerated','Good option when other antibiotics have been tried']},
    # Mixed negative reviews, ranks lower in Antibiotic
    {'id':43,'name':'Metronidazole 400mg','cat':'Antibiotic','mfr':'Abbott','price':45,'disc':0,'stock':280,'rating':4.4,'rx':True,'img':f'{_U}1550572017-edd951b55104?w=300&q=80','tags':'metronidazole anaerobic dental gut infection','reviews':['Dental infection completely resolved quickly excellent','Gut infection treated effectively no recurrence','Doctor prescribed for amoebic infection works well','ઉબકા ખૂબ આવ્યા ખૂબ ખરાબ side effect બેકાર','Avoid alcohol strictly for 48 hours after course','Abbott quality good and widely available','मुँह का स्वाद बहुत खराब हो गया बहुत बुरा अनुभव','Effective for anaerobic bacterial infections good','Complete the full 7 day course as prescribed','Affordable effective first choice antibiotic']},
    {'id':44,'name':'Gripe Water 100ml','cat':'Baby Care','mfr':'Woodwards','price':95,'disc':0,'stock':380,'rating':4.7,'rx':False,'img':f'{_U}1556228720-195a672e8a03?w=300&q=80','tags':'gripe water baby colic gas infant stomach','reviews':['Colic relieved within 10 minutes works brilliantly','Baby stopped crying after first dose amazing','Trusted brand used by mothers for decades','Safe effective for newborns very gentle formula','Pediatrician approved gripe water excellent brand','Gas and bloating in baby resolved quickly','Very gentle on sensitive baby stomach safe','Gives relief during painful colic episodes','Woodwards quality trusted for generations worldwide','Essential item for every new parent recommend']},
    {'id':45,'name':'Baby Teething Gel','cat':'Baby Care','mfr':'Bonjela','price':145,'disc':5,'stock':220,'rating':4.6,'rx':False,'img':f'{_U}1556228720-195a672e8a03?w=300&q=80','tags':'teething gel baby gum pain infant','reviews':['Teething pain relief within 5 minutes excellent','Baby calmed down immediately after applying wonderful','Bonjela quality excellent trusted pediatric brand','Safe formula for babies from 2 months onwards','Pediatrician recommended this brand for teething','Apply on gums with clean finger easy effective','Baby sleeps much better during teething phase','No harmful ingredients in formula reassuring','Works better than other teething remedies tried','Essential item in baby medicine cabinet recommend']},
    {'id':46,'name':'Saline Nasal Drops','cat':'Baby Care','mfr':'Nasivion','price':85,'disc':0,'stock':280,'rating':4.7,'rx':False,'img':f'{_U}1584308666744-24d5c474f2ae?w=300&q=80','tags':'saline nasal drops baby congestion cold infant','reviews':['Blocked nose cleared within minutes works perfectly','Baby breathing much better after each application','Nasivion quality reliable trusted by pediatricians','Safe natural saline solution no side effects','Use before feeding to help baby breathe while eating','Doctor recommended for baby cold and congestion','Very gentle safe from birth onwards excellent','No burning sensation baby does not cry on use','Much safer than decongestant drops for babies','Indispensable for baby cold season recommend']},
    {'id':47,'name':'ORS Electrolyte Sachet','cat':'Baby Care','mfr':'Abbott','price':55,'disc':0,'stock':350,'rating':4.8,'rx':False,'img':f'{_U}1604881988758-f76ad2f7aac1?w=300&q=80','tags':'electrolyte ORS dehydration baby diarrhea','reviews':['Dehydration from diarrhea resolved quickly excellent','Baby recovered very fast with this ORS solution','Pediatrician always recommends Abbott ORS quality','Right electrolyte balance for proper rehydration','Strawberry flavor baby accepts it well happily','Easy to prepare dissolves quickly in water','Abbott quality excellent and trusted for children','Prevented hospital admission with timely ORS use','Keep in baby medicine kit for emergencies always','Much better than homemade ORS for electrolytes']},
    {'id':48,'name':'Magnesium Glycinate 400mg','cat':'Supplements','mfr':'Himalaya','price':420,'disc':5,'stock':160,'rating':4.7,'rx':False,'img':f'{_U}1571772996211-2f02c9727629?w=300&q=80','tags':'magnesium glycinate sleep muscle supplement','reviews':['Sleep quality dramatically improved first week excellent','Muscle cramps completely stopped after 2 weeks great','Anxiety reduced noticeably with consistent daily use','Himalaya quality always reliable well formulated','Best absorbed form of magnesium chelated glycinate','Migraine frequency reduced significantly wonderful','Glycinate form much gentler on stomach than oxide','Energy levels and mood both noticeably improved','Doctor approved for muscle cramps and sleep safe','Best magnesium supplement on Indian market recommended']},
    {'id':49,'name':'Collagen Peptides 10g','cat':'Supplements','mfr':'Wellbeing Nutrition','price':850,'disc':10,'stock':120,'rating':4.6,'rx':False,'img':f'{_U}1571772996211-2f02c9727629?w=300&q=80','tags':'collagen peptides skin joint hair supplement','reviews':['Skin elasticity visibly improved after 8 weeks amazing','Joint pain during exercise significantly reduced excellent','Hair thickness and growth both noticeably improved','Hydrolyzed form for best absorption very effective','Mixes well in water or coffee completely tasteless','Wellbeing Nutrition quality premium highly effective','Nails became much stronger within 6 weeks great','Dermatologist approved ingredient for skin health','Morning routine addition that truly shows results','Best collagen supplement available in India recommended']},
    # Mixed negative reviews, ranks lower in Supplements
    {'id':50,'name':'CoQ10 100mg','cat':'Supplements','mfr':'Natrol','price':680,'disc':5,'stock':130,'rating':4.7,'rx':False,'img':f'{_U}1604881988758-f76ad2f7aac1?w=300&q=80','tags':'CoQ10 coenzyme heart energy antioxidant','reviews':['Energy levels significantly improved after 4 weeks','Cardiologist recommended for patients on statin excellent','Statin muscle pain resolved after adding CoQ10','Natrol quality reliable certified supplement brand','ખૂબ મોંઘું છે ખાસ ફાયદો ન થયો પૈસા બગડ્યા','Heart function improved according to cardiologist','Exercise endurance noticeably better with daily use','बहुत महंगा है और कोई खास फायदा नहीं हुआ बेकार','Antioxidant benefit for overall health longevity','Essential supplement for anyone taking statin medication']},
]


PRODUCT_CATEGORIES = sorted(set(p['cat'] for p in PRODUCTS))

def get_product(pid): return next((p for p in PRODUCTS if p['id']==pid), None)
def get_doctor(did): return next((d for d in DOCTORS if d['id']==did), None)
