# Generated by Django 4.2.7 on 2026-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutprofile',
            options={'verbose_name': 'About Profile'},
        ),
        migrations.AlterField(
            model_name='aboutprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
